Added executables for java 1.7/1.8 on OS X Fixed reverse/reverse complement so it reverses character metadata when whole characters selected Adjust isValid for cloneData to accept of numChars = 0 Have ConsensusTree give better notification if parameters changed Protected against NoClassDefFoundError for Java2D in InfoBar and MesquiteFrame Adjusted ExportForMrBayes so it can save preferred mcmcp search parameter string Reduced unnecessary queries about retaining edited tree Added isDuringNotification to MesquiteThread